### ISSUE TITLE
Investigación de Tecnologías

### ISSUE THREAD

**Issue by santiagoanaya** [nahueldl/TEAyudo#35]
Seguir investigando sobre el buildeo en ios

**Comment by santiagoanaya** [comment]
Con la hackintosh quedaria nada mas que investigar @LPapazian ?

**Comment by LPapazian** [comment]
Falta setear el environment + ver la posibilidad de simular dispositivos, linkeado a #66

**Comment by nahueldl** [comment]
Podemos dar de baja este issue entonces? así vamos limpiando el panel @LPapazian

**Comment by LPapazian** [comment]
Sí, voy a agrupar cosas nuevas bajo el issue de ios
